export enum JobBand {
  BAND_1_MEGA_HUB = 1,
  BAND_2_MAJOR_METRO = 2,
  BAND_3_STRONG_REGIONAL = 3,
  BAND_4_MODERATE = 4,
  BAND_5_RURAL_LOW_VOLUME = 5
}

// Map of US Territory ID to Job Band
export const US_TERRITORY_BAND_MAP: Record<number, JobBand> = {
  // BAND 1: Mega-Hubs (Highest GDP/Population)
  205: JobBand.BAND_1_MEGA_HUB,
  246: JobBand.BAND_1_MEGA_HUB,
  234: JobBand.BAND_1_MEGA_HUB,
  210: JobBand.BAND_1_MEGA_HUB,

  // BAND 2: Major Metros & Corridors
  215: JobBand.BAND_2_MAJOR_METRO,
  240: JobBand.BAND_2_MAJOR_METRO,
  237: JobBand.BAND_2_MAJOR_METRO,
  211: JobBand.BAND_2_MAJOR_METRO,
  235: JobBand.BAND_2_MAJOR_METRO,
  251: JobBand.BAND_2_MAJOR_METRO,
  223: JobBand.BAND_2_MAJOR_METRO,
  250: JobBand.BAND_2_MAJOR_METRO,
  224: JobBand.BAND_2_MAJOR_METRO,
  232: JobBand.BAND_2_MAJOR_METRO,

  // BAND 3: Strong Regional Economies
  203: JobBand.BAND_3_STRONG_REGIONAL,
  245: JobBand.BAND_3_STRONG_REGIONAL,
  216: JobBand.BAND_3_STRONG_REGIONAL,
  222: JobBand.BAND_3_STRONG_REGIONAL,
  227: JobBand.BAND_3_STRONG_REGIONAL,
  206: JobBand.BAND_3_STRONG_REGIONAL,
  225: JobBand.BAND_3_STRONG_REGIONAL,
  243: JobBand.BAND_3_STRONG_REGIONAL,
  253: JobBand.BAND_3_STRONG_REGIONAL,
  201: JobBand.BAND_3_STRONG_REGIONAL,
  220: JobBand.BAND_3_STRONG_REGIONAL,
  219: JobBand.BAND_3_STRONG_REGIONAL,
  239: JobBand.BAND_3_STRONG_REGIONAL,
  238: JobBand.BAND_3_STRONG_REGIONAL,
  247: JobBand.BAND_3_STRONG_REGIONAL,
  207: JobBand.BAND_3_STRONG_REGIONAL,

  // BAND 4: Moderate Markets
  230: JobBand.BAND_4_MODERATE,
  217: JobBand.BAND_4_MODERATE,
  204: JobBand.BAND_4_MODERATE,
  226: JobBand.BAND_4_MODERATE,
  218: JobBand.BAND_4_MODERATE,
  233: JobBand.BAND_4_MODERATE,
  229: JobBand.BAND_4_MODERATE,
  214: JobBand.BAND_4_MODERATE,
  252: JobBand.BAND_4_MODERATE,
  213: JobBand.BAND_4_MODERATE,
  231: JobBand.BAND_4_MODERATE,
  221: JobBand.BAND_4_MODERATE,
  242: JobBand.BAND_4_MODERATE,
  208: JobBand.BAND_4_MODERATE,
  209: JobBand.BAND_4_MODERATE,

  // BAND 5: Low Volume / Rural / Territories
  228: JobBand.BAND_5_RURAL_LOW_VOLUME,
  254: JobBand.BAND_5_RURAL_LOW_VOLUME,
  236: JobBand.BAND_5_RURAL_LOW_VOLUME,
  244: JobBand.BAND_5_RURAL_LOW_VOLUME,
  248: JobBand.BAND_5_RURAL_LOW_VOLUME,
  202: JobBand.BAND_5_RURAL_LOW_VOLUME,
  212: JobBand.BAND_5_RURAL_LOW_VOLUME,
  241: JobBand.BAND_5_RURAL_LOW_VOLUME,
  249: JobBand.BAND_5_RURAL_LOW_VOLUME
};
