export interface USALocation {
  id: number;
  gov_name: string;
  name: string;
}

export const USA_LOCATIONS: USALocation[] = [
  { id: 1, gov_name: 'Alabama', name: 'Alabama' },
  { id: 2, gov_name: 'Alaska', name: 'Alaska' },
  { id: 3, gov_name: 'Arizona', name: 'Arizona' },
  { id: 4, gov_name: 'Arkansas', name: 'Arkansas' },
  { id: 5, gov_name: 'California', name: 'California' },
  { id: 6, gov_name: 'Colorado', name: 'Colorado' },
  { id: 7, gov_name: 'Connecticut', name: 'Connecticut' },
  { id: 8, gov_name: 'Delaware', name: 'Delaware' },
  { id: 9, gov_name: 'District of Columbia', name: 'District of Columbia' },
  { id: 10, gov_name: 'Florida', name: 'Florida' },
  { id: 11, gov_name: 'Georgia', name: 'Georgia' },
  { id: 12, gov_name: 'Guam', name: 'Guam' },
  { id: 13, gov_name: 'Hawaii', name: 'Hawaii' },
  { id: 14, gov_name: 'Idaho', name: 'Idaho' },
  { id: 15, gov_name: 'Illinois', name: 'Illinois' },
  { id: 16, gov_name: 'Indiana', name: 'Indiana' },
  { id: 17, gov_name: 'Iowa', name: 'Iowa' },
  { id: 18, gov_name: 'Kansas', name: 'Kansas' },
  { id: 19, gov_name: 'Kentucky', name: 'Kentucky' },
  { id: 20, gov_name: 'Louisiana', name: 'Louisiana' },
  { id: 21, gov_name: 'Maine', name: 'Maine' },
  { id: 22, gov_name: 'Maryland', name: 'Maryland' },
  { id: 23, gov_name: 'Massachusetts', name: 'Massachusetts' },
  { id: 24, gov_name: 'Michigan', name: 'Michigan' },
  { id: 25, gov_name: 'Minnesota', name: 'Minnesota' },
  { id: 26, gov_name: 'Mississippi', name: 'Mississippi' },
  { id: 27, gov_name: 'Missouri', name: 'Missouri' },
  { id: 28, gov_name: 'Montana', name: 'Montana' },
  { id: 29, gov_name: 'Nebraska', name: 'Nebraska' },
  { id: 30, gov_name: 'Nevada', name: 'Nevada' },
  { id: 31, gov_name: 'New Hampshire', name: 'New Hampshire' },
  { id: 32, gov_name: 'New Jersey', name: 'New Jersey' },
  { id: 33, gov_name: 'New Mexico', name: 'New Mexico' },
  { id: 34, gov_name: 'New York', name: 'New York' },
  { id: 35, gov_name: 'North Carolina', name: 'North Carolina' },
  { id: 36, gov_name: 'North Dakota', name: 'North Dakota' },
  { id: 37, gov_name: 'Ohio', name: 'Ohio' },
  { id: 38, gov_name: 'Oklahoma', name: 'Oklahoma' },
  { id: 39, gov_name: 'Oregon', name: 'Oregon' },
  { id: 40, gov_name: 'Pennsylvania', name: 'Pennsylvania' },
  { id: 41, gov_name: 'Puerto Rico', name: 'Puerto Rico' },
  { id: 42, gov_name: 'Rhode Island', name: 'Rhode Island' },
  { id: 43, gov_name: 'South Carolina', name: 'South Carolina' },
  { id: 44, gov_name: 'South Dakota', name: 'South Dakota' },
  { id: 45, gov_name: 'Tennessee', name: 'Tennessee' },
  { id: 46, gov_name: 'Texas', name: 'Texas' },
  { id: 47, gov_name: 'Utah', name: 'Utah' },
  { id: 48, gov_name: 'Vermont', name: 'Vermont' },
  { id: 49, gov_name: 'Virgin Islands', name: 'Virgin Islands' },
  { id: 50, gov_name: 'Virginia', name: 'Virginia' },
  { id: 51, gov_name: 'Washington', name: 'Washington' },
  { id: 52, gov_name: 'West Virginia', name: 'West Virginia' },
  { id: 53, gov_name: 'Wisconsin', name: 'Wisconsin' },
  { id: 54, gov_name: 'Wyoming', name: 'Wyoming' }
];
